services:
  Richardhj\ContaoAjaxReloadElementBundle\EventListener\AjaxReloadElementListener:
    public: true
    arguments:
      - '@contao.image.picture_factory'
  
  Richardhj\ContaoAjaxReloadElementBundle\EventListener\DataContainer\ModifyPalettesListener:
    public: true
